module.exports = {
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!**/*.d.ts'],
  setupFiles: ['react-app-polyfill/jsdom'],
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.(j|t)s?(x)',
    '<rootDir>/src/**/?(*.)(spec|test).(j|t)s?(x)',
  ],
  testEnvironment: 'jest-environment-jsdom-fourteen',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|ts|tsx)$'],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    '@root(.*)$': '<rootDir>$1',
    '@app(.*)$': '<rootDir>/src/app/$1',
    '@service': '<rootDir>/src/app/lib/service/index',
    '@interface(.*)$': '<rootDir>/src/app/lib/interfaces$1',
    '@lib(.*)$': '<rootDir>/src/app/lib$1',
    '@img(.*)$': '<rootDir>/src/app/style/images$1',
    '@component(.*)$': '<rootDir>/src/app/components$1',
    '@util': '<rootDir>/src/app/lib/utils/index',
    '@decorator': '<rootDir>/src/app/lib/decorators/index',
    '@jsUtil': '<rootDir>/src/app/lib/utils/jsUtil',
  },
  moduleFileExtensions: [
    'web.ts',
    'ts',
    'web.tsx',
    'tsx',
    'web.js',
    'js',
    'web.jsx',
    'jsx',
    'json',
    'node',
    'mjs',
  ],
  globals: {
    'ts-jest': {
      tsConfigFile: '/Users/christian/Desktop/pingAn/bank+/tsconfig.json',
    },
    window: true,
    document: true,
    React: true,
    navigator: true,
  },
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
}
